Added corrections to android getting started guide
MapsPeople/docs pull request #669
Opened 2021-07-09 08:27 UTC by timMikkelsen

2021-07-09 08:59 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +We will start by making a getter for our `MPDirectionsRenderer` the we store on `MapsActivity`
```suggestion
We will start by making a getter for our `MPDirectionsRenderer` that we store on `MapsActivity`:
```

2021-07-09 08:59 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +We start by initializing `MapsIndoors`. `MapsIndoors` is used to get all and store all references to MapsIndoors specific data. This includes access to all MapsIndoors specific Geodata.
```suggestion
We start by initializing `MapsIndoors`. `MapsIndoors` is used to get all and store all references to MapsIndoors-specific data. This includes access to all MapsIndoors-specific geodata.
```

2021-07-09 09:00 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +Place the following initialization code in the `onCreate` method in the `MapsActivity` that displays the Google map. You should also assign the `mapFragment` view to a local variable as we will use t
```suggestion
Place the following initialization code in the `onCreate` method in the `MapsActivity` that displays the Google map. You should also assign the `mapFragment` view to a local variable, as we will use this later to initialize `MapControl` inside the onCreate, after it has been created:
```

2021-07-09 09:01 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +We now want to add all the data we get by initializing `MapsIndoors` to our Google Map. This is done by Initialzing MapControl onto the Google Map. MapControl is used as a layer between Google Maps a
```suggestion
We now want to add all the data we get by initializing `MapsIndoors` to our Google map. This is done by initializing `MapControl` onto the Google map. `MapControl` is used as a layer between Google Maps and MapsIndoors.
```

2021-07-09 09:03 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +Here we use Google Map logic to apply Geodata onto the map. This also means we append logic onto a lot of the Google Maps listeners, which means that using google maps listeners directly might break
```suggestion
Here we use Google Maps logic to apply geodata onto the map. This also means we append logic onto many Google Maps listeners, which means that using Google Maps listeners directly might break intended behavior of the MapsIndoors experience. We recommend to check our reference docs, and see if you can add a specific `Listener` through the `MapControl` and always use those when possible.
```

2021-07-09 09:03 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +Start by creating a `initMapControl` method we will use to initiate the MapControl and assign it to our Google Map:
```suggestion
Start by creating an `initMapControl` method which is used to initiate the `MapControl` and assign it to our Google map:
```

2021-07-09 09:10 UTC, marksdk requested changes

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/map.md
> +In your `onMapReady` callback function, assign the `mMap` variable with the GoogleMap you get from the callback and call the initMapControl method with the `mMapView` you assigned in the `onCreate` t
```suggestion
In your `onMapReady` callback function, assign the `mMap` variable with the `GoogleMap` you get from the callback and call the `initMapControl` method with the `mMapView` you assigned in the `onCreate` to set up a Google map with MapsIndoors Venues, Buildings and Locations:
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +If you do not have a Android device, you can setup an emulator through Android studio, you can see how to do this here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator
```suggestion
If you do not have a Android device, you can setup an emulator through Android studio. You can see how to do that here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator).
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +If you already have a Android device make sure to enable developer mode and USB debugging. Read about this here [Enable USB debugging](https://developer.android.com/studio/debug/dev-options#enable)
```suggestion
If you already have an Android device, make sure to enable developer mode and USB debugging. Read about this here: [Enable USB debugging](https://developer.android.com/studio/debug/dev-options#enable)
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +The basic example contains a single `activity` app with already made `fragments` to host the different logic to get a complete app interracting with a map and `MapsIndoors` data.
```suggestion
The basic example contains a single `activity` app with already made `fragments` to host the different logic to get a complete app interacting with a map and `MapsIndoors` data.
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/new-project.md
> +`play-services-maps` is used for the Google maps which MapsIndoors is build ontop of on Android.
```suggestion
`play-services-maps` is used for Google Maps which MapsIndoors is build on top of on Android.
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/search.md
> +To call our search method with the text in the search input field, we then add an `EditorActionListener` and a `OnClickListener` to the text input field and the search button in the `onCreate` of `Ma
```suggestion
To call our search method with the text in the search input field, we add an `EditorActionListener` and a `OnClickListener` to the text input field, as well as the search button in the `onCreate` of `MapsActivity`.
```

2021-07-09 09:10 UTC, marksdk commented on src/android/v3/getting-started/directions.md
> +We will start by making a getter for our `MPDirectionsRenderer` the we store on `MapsActivity`
```suggestion
We will start by making a getter for our `MPDirectionsRenderer` that we store on `MapsActivity`:
```

2021-07-13 06:46 UTC, WJesper commented on src/android/v3/getting-started/new-project.md
> +If you do not have a Android device, you can setup an emulator through Android studio, you can see how to do this here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator
```suggestion
If you do not have an Android device, you can setup an emulator through Android studio, you can see how to do this here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator).
```

2021-07-13 06:48 UTC, WJesper approved these changes

2021-12-17 12:02 UTC, markhougaard commented on src/android/v3/getting-started/map.md
> +We start by initializing `MapsIndoors`. `MapsIndoors` is used to get all and store all references to MapsIndoors-specific data. This includes access to all MapsIndoors-specific geodata.
```suggestion
We start by initializing `MapsIndoors`. `MapsIndoors` is used to get and store all references to MapsIndoors-specific data. This includes access to all MapsIndoors-specific geodata.
```

2021-12-17 12:02 UTC, markhougaard commented on src/android/v3/getting-started/map.md
> +Place the following initialization code in the `onCreate` method in the `MapsActivity` that displays the Google map. You should also assign the `mapFragment` view to a local variable, as we will use
```suggestion
Place the following initialization code in the `onCreate` method in the `MapsActivity` that displays the Google map. You should also assign the `mapFragment` view to a local variable, as we will use this later to initialize `MapControl` inside the `onCreate`, after it has been created:
```

2021-12-17 12:03 UTC, markhougaard commented on src/android/v3/getting-started/new-project.md
> +If you do not have a Android device, you can setup an emulator through Android studio. You can see how to do that here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator
```suggestion
If you do not have a Android device, you can setup an emulator through Android Studio. You can see how to do that here: [Setting up Android emulator](https://developer.android.com/studio/run/emulator).
```

2021-12-17 12:06 UTC, markhougaard approved these changes

2021-12-17 12:07 UTC, markhougaard commented
@timMikkelsen Very nice! LGTM 👍

2021-12-17 12:10 UTC, merged