Feature/android/thirdpartypositioning
MapsPeople/docs pull request #694
Opened 2021-09-03 07:34 UTC by timMikkelsen

2021-09-08 13:23 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +We will start by implementing logic to each of the implemented methods from the PositionProvider interface. Some of theese will be generic others will be specific to CiscoDNA.
theese

2021-09-08 13:24 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +For a typical Position Provider this mapping from whatever indexing is derived from the positioning, needs to be mapped to the Mapsindoors floor format. However, as the MapsIndoors backend is closely
Mapsindoors <- capitalization :)

2021-09-08 13:32 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Start by creating a method to retrieve the LAN adress:
address spelled wrong

2021-09-08 13:32 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Then the WAN adress, as of now we suggest using a 3rd party service to acquire the WAN adress:
address spelled wrong

2021-09-08 13:33 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Lastly we need the Tenant Id. This is an id you can have hardcoded inside your app or saved as a string resource otherwise you can use the PositionProviderConfig fields from MapsIndoors to get this i
"id" when standing alone should always be capitalized

2021-09-08 13:36 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +All that is left to do now is to start this up after initialising our mapControl.
initializing, spelled in the proper US English way

2021-09-08 13:37 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/google-fused-location-integration.md
> +For Google Fused Location Provider you will need to create a positioning implementation to have the positions received from the api communicate with the MapsIndoors SDK.
"api" should be capitalized

2021-09-08 13:40 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +We'll then start implementing the code to get Indoor Atlas positioning up and running.
Using contraction of "We will" here, despite being the only place in the text where contractions are used. Contractions in written form should be used or not used consistently :)

2021-09-08 13:41 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +For Indoor Atlas to work you will need to supply Indoor Atlas with a api key and a secret key. This can be handled in two ways, if the Indoor Atlas account is setup through MapsPeople we will have th
"api" needs capitalization

2021-09-08 13:44 UTC, fhansenMP commented on src/android/v3/guides/third-party-positioning/google-fused-location-integration.md
> +All that is left to do now is to start this up after initialising our mapControl.
Initializing, in proper US English :P

2021-09-14 12:18 UTC, marksdk requested changes
@timMikkelsen Very nice and thorough guides!

The main part of the suggestions are related to restructuring some of the sentences and wrapping technical terms (methods etc.) in `code`.

Please do note that there might be some paragraphs that are alike across multiple pages, and make sure they are aligned with any suggestions/changes that are made.

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Now we will start implementing the CiscoDNA position provider. Create a class called `CiscoDNAPositionProvider` that implements the PositionProvider interface from the MapsIndoorsSDK, also create a c
```suggestion
Now we will start implementing the CiscoDNA position provider. Create a class called `CiscoDNAPositionProvider` that implements the `PositionProvider` interface from the MapsIndoors SDK. Then create a constructor that takes a context, as well as a String named `tenantId`.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +We will start by implementing logic to each of the implemented methods from the PositionProvider interface. Some of these will be generic others will be specific to CiscoDNA.
```suggestion
We will start by implementing logic to each of the implemented methods from the `PositionProvider` interface. Some of these will be generic, while others will be specific to CiscoDNA.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +The CiscoDNA positioning requires three parameters, the device’s IPv4 address (LAN) and the external IP address of the network in question (WAN), as well as the Tenant ID.
```suggestion
The CiscoDNA positioning requires three parameters:

1. The device’s IPv4 address (LAN)
2. The external IP address of the network in question (WAN)
3. The Tenant ID
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Then the WAN address, as of now we suggest using a 3rd party service to acquire the WAN address:
```suggestion
Then create a method to retrieve the WAN address (we recommend using a 3rd party service for this):
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Lastly we need the Tenant ID. This is an ID you can have hardcoded inside your app or saved as a string resource otherwise you can use the PositionProviderConfig fields from MapsIndoors to get this I
```suggestion
Lastly, we need the Tenant ID. This is an ID you might have hardcoded inside your app, or saved as a string resource. Otherwise you can use the `PositionProviderConfig` fields from MapsIndoors to get this ID like this:
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +If all of the three above mentioned strings can be acquired, you can ask our endpoint for a CiscoDNA Device ID string. A device ID is only available if there has been a recorded positioning for the d
```suggestion
If all of the three above mentioned strings can be acquired, you can ask our endpoint for a CiscoDNA Device ID string. A device ID is only available if there has been a recorded positioning for the device, in the past 24 hours. We will implement this as a new method into our `CiscoDNAPositionProvider`.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +Now you can make a method to start a subscription that we will use when starting positioning to receive position updates. You use the SDKs `LiveDataManager` to create a subscription.
```suggestion
Now you can make a method to start a subscription that we use when starting positioning to receive position updates. You use the SDKs `LiveDataManager` to create a subscription.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/cisco-dna-integration.md
> +To handle the subscription we have just created we need to create some callbacks in the constructor of the PositionProvider to handle the position results and lifecycle of the subscription:
```suggestion
To handle the subscription we just created, we need to create some callbacks in the constructor of the `PositionProvider` to handle the position results and lifecycle of the subscription:
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/google-fused-location-integration.md
> +For Google Fused Location Provider you will need to create a positioning implementation to have the positions received from the API communicate with the MapsIndoors SDK.
```suggestion
For Google Fused Location Provider, you need to create a positioning implementation which enables communicating the positions received from the API with the MapsIndoors SDK.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +The Position Provider should align with the MapsIndoors Floor index convention (floors are indexed as 0, 10, 20, 30, etc. corresponding to ground floor, 1st floor, 2nd floor, 3rd floor, etc., where n
Copy any changes from the same paragraph in Cisco DNA article.

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +We start by implementing a Positioning Provider service. This service is so that in the future you can have mulitple positioning solutions running in the same application and have the code stored in
Copy any changes from the same paragraph in Cisco DNA article.

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +Now we will start implementing the Indoor Atlas position provider. Create a class called IndoorAtlasPositionProvider that implements the PositionProvider interface from the MapsIndoorsSDK, also creat
```suggestion
Now we will start implementing the Indoor Atlas position provider. Create a class called `IndoorAtlasPositionProvider` that implements the `PositionProvider` interface from the MapsIndoors SDK, also create a constructor that takes a context as parameter.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +We will start by implementing logic to each of the implemented methods from the PositionProvider interface.
```suggestion
We will start by implementing logic to each of the implemented methods from the `PositionProvider` interface.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +We start by creating a method to initiate the Indoor Atlas client. Here the method is called initClient.
```suggestion
We start by creating a method to initiate the Indoor Atlas client. Here the method is called `initClient`.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +Create the IAOrientationListener we register in the init method and a positionUpdate method.
```suggestion
Create the `IAOrientationListener` we register in the `init` method and a `positionUpdate` method.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +Create the locationListener referenced in the `startPositioning` and `stopPositioning`:
```suggestion
Create the `locationListener` referenced in the `startPositioning` and `stopPositioning`:
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +Now we need to start up our PositionProvider to get positioning onto our Map. This we will do through our PositionProviderService. We start with creating a method to setup the IndoorAtlas positionPro
```suggestion
Now we need to start up our `PositionProvider` to get positioning onto our Map. This we will do through our `PositionProviderService`. We start with creating a method to setup the IndoorAtlas `positionProvider` from the `PositionProviderService`.
```

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +All that is left to do now is to start this up after initializing our mapControl.
Copy any changes from the same paragraph in Cisco DNA article.

2021-09-14 12:18 UTC, marksdk commented on src/android/v3/guides/third-party-positioning/indoor-atlas-integration.md
> +A full example of the CiscoDNA position provider together with PositionProviderService can be found here: [PositionProviders](https://github.com/MapsPeople/MapsIndoors-Getting-Started-Android/tree/fe
```suggestion
A full example of the CiscoDNA position provider together with `PositionProviderService` can be found here: [PositionProviders](https://github.com/MapsPeople/MapsIndoors-Getting-Started-Android/tree/feature/third_pary_position_providers/app/src/main/java/com/example/mapsindoorsgettingstarted/PositionProviders)
```

2021-09-24 09:04 UTC, timMikkelsen reviewed
Went through the requested changes. Can't seem to find where to "accept" them as i had to do some of them manually.

2021-09-24 09:17 UTC, markhougaard approved these changes
Great job @timMikkelsen 👏

2021-09-24 09:23 UTC, merged