Feature/android/auth/sso
MapsPeople/docs pull request #737
Opened 2021-12-03 10:15 UTC by timMikkelsen

2021-12-03 10:22 UTC, fhansenMP commented on src/android/v3/guides/using-authentication-in-mapsindoors.md
> +After you have made the request if using the library you will have to react on the recieved intent from the user loggin in.
spelling mistake: loggin -> logging

2021-12-03 10:24 UTC, fhansenMP commented on src/android/v3/guides/using-authentication-in-mapsindoors.md
> +The SDK will then make sure that all requests for data is performed using this access token.
The SDK will ensure all subsequent performed data requests will include the set access token.

2021-12-03 10:46 UTC, ChristianWolf-mapspeople requested changes

2021-12-03 10:46 UTC, ChristianWolf-mapspeople commented on src/android/v3/guides/using-authentication-in-mapsindoors.md
> +            //An error happened authentication was not succesful.
```suggestion
            //An error happened, authentication was not succesful.
```

2021-12-03 10:46 UTC, ChristianWolf-mapspeople commented on src/android/v3/guides/using-authentication-in-mapsindoors.md
> +            //An error happened authentication was not succesful.
```suggestion
            //An error happened, authentication was not succesful.
```

2021-12-03 11:49 UTC, ChristianWolf-mapspeople approved these changes

2021-12-06 09:24 UTC, ChristianWolf-mapspeople approved these changes

2021-12-06 09:37 UTC, fhansenMP approved these changes

2021-12-06 09:38 UTC, merged