feat: Add documentation for SSO in the JavaScript SDK.
MapsPeople/docs pull request #742
Opened 2021-12-10 12:25 UTC by eNepper

2021-12-10 12:29 UTC, markhougaard requested changes

2021-12-10 12:29 UTC, markhougaard commented on src/web/v4/guides/authentication/index.md
> +> Note that the access token obtained from a MapsIndoors Single Sign-on flow cannot be used as access token for the [Booking Service](../booking). Single Sign-on access tokens are issued by MapsIndoo
@eNepper Watch out for the relative link to "Booking Service". It's much better to make it an absolute link, so it doesn't break when I or someone else moves stuff around next time.

2021-12-10 14:27 UTC, eNepper commented on src/web/v4/guides/authentication/index.md
> +> Note that the access token obtained from a MapsIndoors Single Sign-on flow cannot be used as access token for the [Booking Service](../booking). Single Sign-on access tokens are issued by MapsIndoo
I copied that from the iOS documentation :)

2021-12-13 07:40 UTC, eNepper commented on src/web/v4/guides/authentication/index.md
> +> Note that the access token obtained from a MapsIndoors Single Sign-on flow cannot be used as access token for the [Booking Service](../booking). Single Sign-on access tokens are issued by MapsIndoo
I have removed the link because we don't have that document for the JavaScript SDK yet.

2021-12-13 07:56 UTC, markhougaard approved these changes

2021-12-13 12:52 UTC, merged