MIGEN-2054-Update/webv4 gettingstarted
MapsPeople/docs pull request #760
Opened 2022-01-12 09:12 UTC by JG1995

Major updates to primarily code examples (MIGEN-2054) and restructure of "Guides" menu point (MIGEN-2058)

2022-01-12 13:04 UTC, markhougaard requested changes

2022-01-12 13:04 UTC, markhougaard commented on src/web/v4/getting-started/map.md
> +To load data and display it on the map, we need to create a new _instance_ of the [`MapsIndoors` class](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/mapsindoors.MapsIndoors.html#MapsInd
```suggestion
To load data and display it on the map, we need to create a new _instance_ of the [`MapsIndoors` class](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/mapsindoors.MapsIndoors.html#MapsIndoors) with a [`mapView` instance](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/mapsindoors.mapView.GoogleMapsView.html#GoogleMapsView) with a few _properties_ set. This is all done by placing the following code in the `main.js` file you created earlier:
```

2022-01-12 13:04 UTC, markhougaard commented on src/web/v4/getting-started/new-project.md
```suggestion
```

2022-01-12 13:04 UTC, markhougaard commented on src/web/v4/getting-started/new-project.md
> +1. While not strictly neccesary, if you do not have prior development experience, it is advised to install an integrated development environment (IDE). A common one to use is [Visual Studio Code](htt
```suggestion
1. While not strictly neccesary, if you do not have prior development experience, it is advised to install an Integrated Development Environment (IDE). A common one to use is [Visual Studio Code](https://code.visualstudio.com/), which is free.
```

2022-01-12 13:04 UTC, markhougaard commented on src/web/v4/guides/index.md
> +You might have come here directly after the "Getting Started" guide, or you might just wish to use these guides at your own pace - Regardless, here is a structured overview over what you can find in
```suggestion
You might have come here directly after the "Getting Started" guide, or you might just wish to use these guides at your own pace. Regardless, here is a structured overview over what you can find in these guides. You can also navigate between them in the sidebar to the left.
```

2022-01-12 13:27 UTC, markhougaard requested changes

2022-01-12 13:27 UTC, markhougaard commented on src/shared/getting-started/overview.md
> +Parts of this guide rely on having access to a MapsIndoors Dataset which supports Live Data Integration, if you do not have access to this through your own Solution, we recommend using our demo API k
@JG1995 Reading this again, I'm wondering if we should change some of the terminology used; "Dataset" == "Solution" which in turn is accessed with an "API key". Here's a suggestion:

```suggestion
Parts of this guide rely on having access to a MapsIndoors Solution which supports Live Data Integration. If you do not have access to this through your own Solution, we recommend using our demo API key to access one: `{{sdk.tutorialAPIKey}}`.
```

How does that sound to you?

2022-01-12 13:27 UTC, markhougaard commented on src/web/v4/getting-started/map.md
> +The MapsIndoors SDK is hosted on a content delivery network (CDN) and should be loaded using a script tag.
```suggestion
The MapsIndoors SDK is hosted on a Content Delivery Network (CDN) and should be loaded using a script tag.
```

2022-01-12 13:27 UTC, markhougaard commented on src/web/v4/getting-started/map.md
> +<!-- FIGURE OUT HOW TO FIX THE HIGHLIGHTING - IT'S THE <> THAT ARE DOING IT - POTENTIAL FIX MY MAKING IT ONE LINE, IT DOESNT LIKE SPLIT <> -->
@JG1995 Remember this comment 🙂

2022-01-12 13:27 UTC, markhougaard commented on src/web/v4/getting-started/map.md
> +<!-- FIGURE OUT HOW TO FIX THE HIGHLIGHTING - IT'S THE <> THAT ARE DOING IT - POTENTIAL FIX MY MAKING IT ONE LINE, IT DOESNT LIKE SPLIT <> -->
@JG1995 Remember this comment

2022-01-12 13:27 UTC, markhougaard commented on src/web/v4/guides/index.md
> +**NOTE: These guides are for the web-version of the SDK, but we also have extensive documentation for the SDK for iOS and Android.**
```suggestion
**Note: These guides are for the web-version of the SDK, but we also have extensive documentation for the SDK for iOS and Android.**
```

2022-01-12 13:29 UTC, JG1995 commented on src/web/v4/getting-started/map.md
> +<!-- FIGURE OUT HOW TO FIX THE HIGHLIGHTING - IT'S THE <> THAT ARE DOING IT - POTENTIAL FIX MY MAKING IT ONE LINE, IT DOESNT LIKE SPLIT <> -->
I know, I made a temporary fix for the time being

2022-01-12 13:44 UTC, markhougaard commented on src/web/v4/getting-started/map.md
> +<!-- FIGURE OUT HOW TO FIX THE HIGHLIGHTING - IT'S THE <> THAT ARE DOING IT - POTENTIAL FIX MY MAKING IT ONE LINE, IT DOESNT LIKE SPLIT <> -->
@JG1995 Can we remove this comment and the other one like it then?

2022-01-13 08:56 UTC, markhougaard approved these changes

2022-01-13 09:18 UTC, merged