Feature/password reset 2fa
MapsPeople/docs pull request #763
Opened 2022-01-17 13:37 UTC by JG1995

should still feature the relevant changes from the previous PR, but updated 2FA page to fit actual needs (ie. CMS tutorial)

2022-01-18 13:08 UTC, MikaelElkiaer commented on src/web/v4/guides/authentication/2fa.md
> +### Disabling 2FA on behalf of a user
I don't think this should be in the public doc. At the most it should say something about contacting someone at MapsPeople in order to help disabling 2FA.

2022-01-18 13:09 UTC, MikaelElkiaer reviewed
Just had the 1 comment. Regarding the CMS doc, I don't have much of an opinion.

2022-01-19 07:28 UTC, MikaelElkiaer commented on src/web/v4/guides/authentication/2fa.md
> +### Disabling 2FA on behalf of a user
@JG1995

2022-01-19 07:33 UTC, JG1995 commented on src/web/v4/guides/authentication/2fa.md
> +### Disabling 2FA on behalf of a user
I can remove the second part about if the user loses access, and just ask them to defer to us, but the part about the user self-disabling is literally in the CMS, so I feel like it would be weird not to mention it.

2022-01-19 07:35 UTC, MikaelElkiaer commented on src/web/v4/guides/authentication/2fa.md
> +### Disabling 2FA on behalf of a user
I was only referring to the section `### Disabling 2FA on behalf of a user`.

2022-01-19 07:36 UTC, JG1995 commented on src/web/v4/guides/authentication/2fa.md
> +### Disabling 2FA on behalf of a user
Ah alright, the other part was just included in the snippet GitHub highlighted, will push a fix in a moment

2022-01-19 13:57 UTC, markhougaard requested changes
Let me know if you have any questions to the suggestions here.

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/2fa.md
> +Enabling 2-Factor Authentication (2FA) is done by the user themselves via the CMS. If a user clicks their avatar in the top-right corner, a drop-down menu will appear, where "Settings" should be clic
```suggestion
You can enable 2-Factor Authentication (2FA) in the MapsIndoors CMS. Click the avatar in the top-right corner, and click on "Settings". Follow the instructions to enable 2FA.
```

We should talk to the user, not about them. It makes the sentences shorter and it's easier to write in the [active voice](https://www.grammarly.com/blog/active-vs-passive-voice/) when addressing someone directly.

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/2fa.md
> +Once 2FA is enabled, this page will change to allow disabling of 2FA, should the user want to do this at a later point. Simply follow the instructions on the page.
```suggestion
After you've enabled 2FA, the page will show instructions on how to disable 2FA again.
```

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/2fa.md
> +If you, or a user, loses access to your account and are unable to use 2FA for any reason, please contact your representative at MapsPeople, and we will work with you to find a solution.
```suggestion
If you lose access to your account and are unable to use 2FA for any reason, please [get in touch](https://resources.mapspeople.com/contact-us), and we'll do our best to find a solution.
```

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/2fa.md
> +If you, or a user, loses access to your account and are unable to use 2FA for any reason, please contact your representative at MapsPeople, and we will work with you to find a solution.
Whenever there's a call-to-action on getting in touch, I try to include a link to the page on our website or Support Portal.

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/password-reset.md
> +Any user can reset their password via [https://auth.mapsindoors.com/login/forgotpassword](https://auth.mapsindoors.com/login/forgotpassword). After submitting an e-mail address, a token is generated
```suggestion
You can reset your password via [https://auth.mapsindoors.com/login/forgotpassword](https://auth.mapsindoors.com/login/forgotpassword). Submit your e-mail address, and we'll send you a link to reset your password.
```

2022-01-19 13:57 UTC, markhougaard commented on src/web/v4/guides/authentication/password-reset.md
> +Token expiration is currently set to 1 hour, individually set for each token upon requesting a password reset.
```suggestion
Enter your password twice on the Password Reset page to change it.
```

2022-01-20 11:14 UTC, markhougaard approved these changes

2022-01-20 11:28 UTC, merged