updated Language docs for mobile, created one for Web
MapsPeople/docs pull request #766
Opened 2022-01-19 12:39 UTC by JG1995

Despite a lot of confusion, I think I managed to compile some doc on languages based on the many questions I had about it, but absolutely tell me if you feel something important is missing, or I misunderstood something.

I requested multiple reviewers, but of course just look at the part that you actually work with, be that iOS, Android or Web.

2022-01-19 12:48 UTC, matiasholst submitted a review, later dismissed

2022-01-20 09:05 UTC, hyperzpace commented on src/android/v3/guides/display-language.md
> +Addionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as using individual localised strings.
```suggestion
Additionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as using individual localised strings.
```

2022-01-20 09:06 UTC, hyperzpace commented on src/android/v3/guides/display-language.md
> +Addionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as using individual localised strings.
Also, "aside from methods mentioned here" seems redundant, no? It sounds like you already mention this somewhere else before this section.

2022-01-20 09:07 UTC, hyperzpace commented on src/android/v3/guides/display-language.md
> +Addionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as using individual localised strings.
`localised ` should probably also be `localized `. We seem to be using US conventions.

2022-01-20 09:12 UTC, hyperzpace commented on src/shared/display-language/cms-language.md
> +To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", this translation must be provided by the user in the CMS. A translation can be provided in any la
```suggestion
To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", the translation must be provided by the user in the CMS. A translation can be provided in any language, and any pre-defined phrase will default to English. In order to add non-default languages, please contact your MapsIndoors representative, and we will enable you to add translations in your desired language.
```

2022-01-20 09:12 UTC, hyperzpace commented on src/shared/display-language/cms-language.md
> +To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", this translation must be provided by the user in the CMS. A translation can be provided in any la
Hi @JG1995 

Can you elaborate on what "any pre-defined phrase will default to English" means?

2022-01-20 09:18 UTC, hyperzpace commented on src/web/v4/guides/display-language.md
> +The web-app will also automatically adjust the language to the language set in the user's browser settings, or failing that, the device settings. This is limited to the following languages, and will
```suggestion
The web-app will automatically adjust the language to the language set in the user's browser settings, otherwise default to English. If the user is using macOS, the device's language settings will be used. This is limited to the following languages, and will default to English if the selected language is not supported:
```

2022-01-20 09:28 UTC, hyperzpace commented on src/web/v4/guides/display-language.md
> +The web-app will also automatically adjust the language to the language set in the user's browser settings, or failing that, the device settings. This is limited to the following languages, and will
```suggestion
The web-app will automatically adjust the language to the language set in the user's browser settings, otherwise default to English. When using Safari, the device's language setting will be used. This is limited to the following languages, and will default to English if the selected language is not supported:
```

2022-01-20 10:05 UTC, JG1995 commented on src/android/v3/guides/display-language.md
> +Addionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as using individual localised strings.
> Also, "aside from methods mentioned here" seems redundant, no? It sounds like you already mention this somewhere else before this section.

I think it's neccesary since it's in the precursor text. Had it been after the methods listed I would have agreed with you.

2022-01-20 10:07 UTC, JG1995 commented on src/shared/display-language/cms-language.md
> +To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", this translation must be provided by the user in the CMS. A translation can be provided in any la
I think that's a previous wording from while I was still barely understanding it, I'll reword or just remove.

2022-01-20 10:23 UTC, ChristianWolf-mapspeople requested changes

2022-01-20 10:23 UTC, ChristianWolf-mapspeople commented on src/ios/v3/guides/display-language/index.md
> +Addionally, aside from methods mentioned here, you can provide translations via the standard method for your device, such as `LocalizedString`.
```suggestion
Additionally, aside from methods mentioned here, you can provide translations via the standard method for iOS, `LocalizedString`.
```

2022-01-20 11:35 UTC, hyperzpace commented on src/shared/display-language/cms-language.md
> +To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", the translation must be provided by the user in the CMS. A translation can be provided in any lan
```suggestion
To provide multiple languages for items in the MapsIndoors CMS, such as "Meeting Room" or "Restroom", the translation must be provided by the user in the CMS. A translation can be provided in any language. In order to add support for additional languages that we currently do not support, please contact your MapsIndoors representative, and we will enable you to add translations in your desired language.
```

2022-01-20 11:39 UTC, hyperzpace approved these changes

2022-01-20 11:50 UTC, ChristianWolf-mapspeople approved these changes
Approval of the iOS part

2022-01-20 11:53 UTC, merged