Feature/app user roles
MapsPeople/docs pull request #774
Opened 2022-01-28 09:32 UTC by JG1995

Need general review, but mainly Android and Web - iOS section has been pre-approved by Christian.

2022-01-28 09:44 UTC, fhansenMP commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
... User Roles _(is)_ a feature of the MapsIndoors _(SDK/Platform?)_...

2022-01-28 09:45 UTC, fhansenMP commented on src/various/app-user-roles.md
> +App User Roles are confuigured via the CMS web application. In the menus, go to `Solution Details > App Settings > App Configuration`, and then find the menu point named `App User Roles`. Here, you c
configured spelling error

2022-01-28 10:01 UTC, JG1995 commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
"are" is correct, added "platform"

2022-01-28 10:03 UTC, fhansenMP commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
_are a feature_ describes a singular feature, so _"is"_ is correct.

2022-01-28 10:07 UTC, JG1995 commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
No, the "are" refers back to the "app user roleS", which are plural, it's not the singular feature which determines the singular/plural (Shahab agrees).

"Is" would be correct if the sentence was something like "An app user role (singular) is a feature within MapsIndoors"

2022-01-28 10:10 UTC, fhansenMP commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
User Roles is capitalized, meaning it is the (singular) _feature_ being described. User Roles is the name of the feature - and being a feature, it is singular.

2022-01-28 10:11 UTC, fhansenMP commented on src/various/app-user-roles.md
> +Application User Roles are a feature of the MapsIndoors where you can define roles that you can assign to your users. This will impact various features of the app, for example, if certain doors can o
But I don't really care, we can see it as resolved...

2022-01-28 11:02 UTC, fhansenMP submitted a review, later dismissed

2022-01-28 13:15 UTC, markhougaard requested changes

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +The App User Roles are a useful tool to limit which types of users can see certain Locations. The main fields that can be influenced through the App User Rules are the Locations on the Map itself, wh
```suggestion
The App User Roles are useful for setting limits on who can find certain Locations. App User Rules influence the map in three ways; which Locations are displayed on the map, whether they show up in search results, and the directions you can get.
```

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +Any Location defined on the map, in the menu, there is a section named `Restrictions`, where you are presented with options for limiting certain App User Roles.
@JG1995 Not sure I completely follow this sentence. Could you try rephrasing it please?

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +* **Open for specific App User Roles** - Here you will see an overview of the App User Roles you have set up previously. Using the checkboxes you can define which App User Roles should have access to
```suggestion
* **Open for specific App User Roles** - Select which App User Roles have access to viewing, searching and getting directions to this specific Location.
```

Cut, cut, cut 🙂

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +As mentioned previously, App User Roles can be used to determine which passages can be taken by a given role. Specifically for "Entrance" Location types, the Restrictions will define whether or not a
Hmm, no 🙂

All Location Types are created equal. It doesn't matter what its name is. There is a difference between a Location and a Route Element, however—the former is geodata, the latter is a modifier on the Graph Layer affecting directions.

My suggestion for what to write in this section:

```suggestion
App User Roles can be used to determine the directions users get. For instance, you can restrict Doors between two Locations to only be passable by a certain App User Role.

Note: If you restrict a Room to only be accessible to certain App User Roles, you restrict both directions _to_ and _through_ that Room. It effectively sets restrictions on all Doors leading to that Room as well.
```

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +If a Location has been restricted to certain App User Roles, it will not be displayed on the Map for those who do not have permission.
```suggestion
If a Location has been restricted to certain App User Roles, it will not be displayed on the map for those who do not have permission.
```

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +Similarly to the effect on the Map, if a Location has restrictions, it will not show up in a Search for users without sufficient permissions.
```suggestion
Similarly to the effect on the map, if a Location has restrictions, it will not show up in the search results for users without sufficient permissions.
```

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +* **Closed for All** - No users will see this Location on the Map.
```suggestion
* **Closed for All** - No users will see this Location on the map.
```

2022-01-28 13:15 UTC, markhougaard commented on src/various/app-user-roles.md
> +* **Open for all** - All App User Roles can view and search for this Location.
```suggestion
* **Open for all** - All users can view, search for, and get directions to this Location.
```

2022-01-31 06:53 UTC, JG1995 commented on src/various/app-user-roles.md
> +* **Closed for All** - No users will see this Location on the Map.
Other places in the documentation (also old stuff that I haven't touched yet) we capitalise map, like we would Location, for example... I can leave it uncapitalised going forward, no issue, just a heads up

2022-01-31 07:07 UTC, JG1995 commented on src/various/app-user-roles.md
> +Any Location defined on the map, in the menu, there is a section named `Restrictions`, where you are presented with options for limiting certain App User Roles.
You already made suggestions (which I comitted) for these sentences though?

2022-02-02 13:42 UTC, markhougaard requested changes

2022-02-02 13:42 UTC, markhougaard commented on src/various/app-user-roles.md
> +Any Location defined on the map, in the menu, there is a section named `Restrictions`, where you are presented with options for limiting certain App User Roles.
Not this in particular, which I'm still not grasping the meaning of:

> Any Location defined on the map, in the menu, there is a section named `Restrictions`, where you are presented with options for limiting certain App User Roles.

2022-02-02 14:11 UTC, hyperzpace commented on src/various/app-user-roles.md
> +_Application User Roles_ are a feature that lets you define various roles you can assign to your users, or they can choose between themselves.
```suggestion
_Application User Roles_ is a feature that lets you define various roles you can assign to your users, or they can choose between themselves.
```

It's one feature, no?

2022-02-02 14:15 UTC, hyperzpace commented on src/various/app-user-roles.md
> +Click `Add App User Role` and enter the name of the newly created Role in all defined languages for your Solution.
This sentence makes it sound like it's mandatory to fill in the name for all languages.

2022-02-02 14:16 UTC, hyperzpace commented on src/various/app-user-roles.md
> +Assigning or changing App User Roles to users is done in the app itself. The method depends on which platform you're developing for. Here are some examples:
```suggestion
Assigning or changing `App User Roles` to users is done in the app itself. The method depends on which platform you're developing for. Here are some examples:
```

2022-02-02 14:17 UTC, hyperzpace commented on src/various/app-user-roles.md
> +The App User Roles are useful for setting limits on who can find certain Locations. App User Rules influence the map in three ways; which Locations are displayed on the map, whether they show up in s
```suggestion
The `App User Roles` is useful for setting limits on who can find certain `Locations`. `App User Rules` influence the map in three ways; which Locations are displayed on the map, whether they show up in search results, and the directions you can get.
```

2022-02-02 14:21 UTC, hyperzpace commented
Hey @JG1995 :)

I'm not sure what's been agreed upon, but as far as I understand, we typically highlight words like Location, Solution etc., so wrapping them in `backticks` is preferable. Is this correct, @markhougaard?

2022-02-02 14:22 UTC, JG1995 commented
> Hey @JG1995 :)
> 
> I'm not sure what's been agreed upon, but as far as I understand, we typically highlight words like Location, Solution etc., so wrapping them in `backticks` is preferable. Is this correct, @markhougaard? 

You're 100% correct, I think I just forgot!

2022-02-02 14:23 UTC, JG1995 commented
> Hey @JG1995 :)
> 
> I'm not sure what's been agreed upon, but as far as I understand, we typically highlight words like Location, Solution etc., so wrapping them in `backticks` is preferable. Is this correct, @markhougaard? 

I agreed with Mark that we just capitalise them I think?

2022-02-02 14:24 UTC, hyperzpace commented
Oh. Well, I'm not sure. I just noticed that you only used `backticks` when mentioning App User Roles sometimes.

2022-02-02 14:26 UTC, hyperzpace commented
Great work, though! It seems to be coming together quite nicely and it's easy to understand 👍🏼

2022-02-02 14:34 UTC, markhougaard commented
> > Hey @JG1995 :)
> > I'm not sure what's been agreed upon, but as far as I understand, we typically highlight words like Location, Solution etc., so wrapping them in `backticks` is preferable. Is this correct, @markhougaard?
> 
> I agreed with Mark that we just capitalise them I think?

Yes, if it's a mention of e.g. a function in the SDK like `setVenue`, backticks make sense. If it's Location, Room etc. they're just capitalized.

2022-02-04 10:30 UTC, JG1995 commented
> Oh. Well, I'm not sure. I just noticed that you only used `backticks` when mentioning App User Roles sometimes.

That's only when it's literally a menu point named App User Roles, which is referred to once or twice, when mentioned outside of a specific menu point it's in plaintext :-)

2022-02-07 09:11 UTC, markhougaard approved these changes

2022-02-07 09:13 UTC, merged