Feature/custom properties
MapsPeople/docs pull request #780
Opened 2022-02-07 11:42 UTC by JG1995

Updated doc for custom properties

2022-02-07 12:01 UTC, ChristianWolf-mapspeople requested changes

2022-02-07 12:01 UTC, ChristianWolf-mapspeople commented on src/various/custom-properties.md
> +<mi-tabs>
As the examples are being shown side by side, it would make sense to use the same example instead of three different examples.

2022-02-07 12:13 UTC, markhougaard requested changes

2022-02-07 12:13 UTC, markhougaard commented on src/various/custom-properties.md
> +Using the above screenshot as an example basis - To fetch the `value` value of a custom property (also known as the `field`), you use `location.properties.fields[key].value`. In an example, that woul
```suggestion
Using the above screenshot as an example, you fetch the `value` value of a custom property (also known as the `field`) with `location.properties.fields[key].value`. In code, it could look like this:
```

2022-02-07 12:13 UTC, markhougaard commented on src/various/custom-properties.md
> +<mi-tabs>
I second that 🙂

2022-02-07 12:19 UTC, JG1995 commented on src/various/custom-properties.md
> +<mi-tabs>
We can absolutely do that, but then you'll have to supply me with said examples 😉 I think currently Android is the best and clearest one, so I'd argue it makes sense to use that as a baseline. I can fairly easily rework the Web one to match that structure, but iOS code makes no sense to me, bluntly speaking...

2022-02-08 07:49 UTC, ChristianWolf-mapspeople commented on src/various/custom-properties.md
> +<mi-tabs>
Replicating the Android (Java) examples for iOS (Swift):

---

```swift
let data = location.getField(forKey: "field name")
```

To retrieve individual segments of the property, you can use:

```swift
let text = data.text
let value = data.value
let type = data.type
```

2022-02-08 09:12 UTC, JG1995 commented on src/various/custom-properties.md
> +<mi-tabs>
Thank you Christian :-) @markhougaard can you give me something similar for the web app? It wasn't as straightforward to do myself as I'd hoped...

2022-02-08 09:39 UTC, markhougaard commented on src/various/custom-properties.md
> +<mi-tabs>
@JG1995 Please ask a web developer to provide you with the examples you need.

2022-02-08 10:26 UTC, ChristianWolf-mapspeople reviewed
Strictly speaking, the image named `src/assets/various/custom-properties-android.png` is not Android since it is from the CMS.
It just messes with my head to see an "Android" image referenced in all platforms when it is not platform specific 😄

2022-02-08 10:35 UTC, JG1995 commented
> Strictly speaking, the image named `src/assets/various/custom-properties-android.png` is not Android since it is from the CMS. It just messes with my head to see an "Android" image referenced in all platforms when it is not platform specific 😄

Fixed it just for you @ChristianWolf-mapspeople 😉

2022-02-08 11:41 UTC, ChristianWolf-mapspeople requested changes

2022-02-08 11:41 UTC, ChristianWolf-mapspeople commented on src/various/custom-properties.md
> +let data = location.getField(forKey: "field name")
To be completely consistent:

```suggestion
let data = location.getField(forKey: "email")
```

2022-02-08 11:41 UTC, ChristianWolf-mapspeople commented on src/various/custom-properties.md
> +DataField data = location.getField("field name");
To be completely consistent:

```suggestion
DataField data = location.getField("email");
```

2022-02-08 12:11 UTC, ChristianWolf-mapspeople submitted a review, later dismissed
Looking good!

2022-02-08 15:21 UTC, markhougaard approved these changes

2022-02-08 16:33 UTC, merged