Feature/android/1315/directions detailed guide
MapsPeople/docs pull request #787
Opened 2022-02-21 08:08 UTC by timMikkelsen

2022-02-21 10:11 UTC, JG1995 requested changes
This is mostly wording changes and grammar fixes, but give them a read to make sure I didn't accidentally change the meaning of the descriptions in my rewording.

2022-02-21 10:11 UTC, JG1995 commented on src/android/v3/guides/directions/directions-wayfinding-instructions.md
> +We will work with changing the implementation of the `NavigationFragment` and the `RouteLegFragment`.
```suggestion
You will work with changing the implementation of the `NavigationFragment` and the `RouteLegFragment`.
```

2022-02-21 10:11 UTC, JG1995 commented on src/android/v3/guides/directions/directions-wayfinding-instructions.md
> +Now we will replace the old view in the `RouteLegFragment`.
```suggestion
Next step is replacing the old view in the `RouteLegFragment`.
```

2022-02-21 10:11 UTC, JG1995 commented on src/android/v3/guides/directions/directions-wayfinding-instructions.md
> +We will now change the `ViewPager` implementation to contain the revised `RouteLegFragment` for each leg of the route.
```suggestion
Next step is to change the `ViewPager` implementation to contain the revised `RouteLegFragment` for each leg of the route.
```

2022-02-21 10:11 UTC, JG1995 commented on src/android/v3/guides/directions/directions-wayfinding-instructions.md
> +We will now update the `onViewCreated` method to use the new views added earlier in the tutorial.
```suggestion
You must also update the `onViewCreated` method to use the new views added earlier in the tutorial.
```

2022-02-21 14:23 UTC, timMikkelsen commented on src/android/v3/guides/directions/directions-renderer.md
> +It is possible to show contextual information on the end points of the rendered path of a route segment by configuring the directions renderer to look for nearby Locations or POIs.
This is not correct. It is only the marker/label on the map that is changed. Directions remain unchanged.

2022-02-21 14:28 UTC, timMikkelsen commented on src/android/v3/guides/directions/directions-renderer.md
> +The defaults of the `ContextualInfoSettings` builder is `maxDistance` at 5 meters and the `ContextualInfoScope` as icon and name. No Types or Categories is set as default. Not applying any will make
Types _or_ Categories? 😄

2022-02-22 07:38 UTC, JG1995 commented on src/android/v3/guides/directions/directions-renderer.md
> +It is possible to show contextual information on the end points of the rendered path of a route segment by configuring the directions renderer to look for nearby Locations or POIs.
Alright, ignore this suggestion then.

2022-02-22 07:40 UTC, JG1995 approved these changes

2022-02-22 08:07 UTC, merged