WIP: Feature/mapcentric cms live
MapsPeople/docs pull request #806
Opened 2022-03-23 12:29 UTC by JG1995

Should be ready for review, content-wise - In time I will probably create a page structure to make it more accessible, but for the purpose of it just being ready, this will have to do.

2022-03-23 13:54 UTC, markhougaard commented on src/cms/index.md
> +Your data is structured in a hierarchy where the top level is your Solution which can contain multiple Venues, which in turn can have multiple Buildings and so on. The data-types in hierarchical orde
```suggestion
Your data is structured in a hierarchy where the top level is your Solution which can contain multiple Venues, which in turn can have multiple buildings and so on. The data-types in hierarchical order, and a short description:
```

2022-03-23 14:17 UTC, Chatrine commented on src/cms/index.md
> +The MapsIndoors Content Management System (CMS) is the platform through which you edit your Maps, Locations, POI's and more.
The MapsIndoors Content Management System (CMS) enables you to add, edit, and maintain your location data within the MapsIndoors platform.

2022-03-23 14:25 UTC, Chatrine commented on src/cms/index.md
> +Using the CMS is much less technical than the process of developing an app for Android, iOS or Web, and should be usable by almost anyone, no matter your background - No skills in programming are nee
I get what you want to emphasize here, but I don think we can formulate it in such a way where it does not alienize someone. Therefore, I think we can leave out this section.

2022-03-23 14:30 UTC, Chatrine commented on src/cms/index.md
> +Your data is structured in a hierarchy where the top level is your Solution which can contain multiple Venues, which in turn can have multiple Buildings and so on. The data-types in hierarchical orde
Could leave out the "_, and a short description_", or maybe alternatively write "_... in hierarchical order (with description):_" instead.

2022-03-23 14:36 UTC, Chatrine commented on src/cms/index.md
> +  * A Solution is the topmost level of your data structure. It encompasses all of the Venues, Building and Locations that you need for your MapsIndoors implementation. It is possible to have more tha
```suggestion
  * A Solution is the topmost level of your data structure. It encompasses all of the Venues, Buildings and Locations that you need for your MapsIndoors implementation. It is possible to have more than one solution, but for the mast vajority of use-cases, you will just have one.
```

2022-03-23 15:10 UTC, Chatrine commented on src/cms/index.md
> +  * A Venue is the second level of data. A Venue might consist of only one Building, but it could also consist of several, for example, a university campus might be many Buildings, but it is all cons
I would like a different structure of this section. First it should describe Venues in relation to Solutions, and afterwards Venues in relation to Buildings, giving it a smoother transition between the section before and after. 
Moreover, I think it would make sense to replace the University example with an example from one of of our two main verticals: Corporate offices, or Sports & Entertainment.

**Example of restructure:**
A Venue is the second level of data. You can have multiple Venues in one solution. For example, a university might have multiple campuses spread over the city. Each of these could be a Venue, but under the same solution. A Venue can consist of one or more Buildings. For example, a university campus might be many Buildings, but it is all considered the same Venue.

2022-03-24 07:35 UTC, Chatrine commented on src/cms/index.md
> +  * A Building is a data type that is a collection of Floors. Buildings are slightly less abstract than Solutions and Venues, as they are just that - a Building, both in real life and in the MapsIndo
```suggestion
  * A Building is a collection of Floors. Inside a Venue you can have one or more Buildings and an Outside area. Outside is categorized together with Buildings, because it is a part of what comprises a Venue.
```

2022-03-24 07:36 UTC, Chatrine commented on src/cms/index.md
> +  * A Building is a data type that is a collection of Floors. Buildings are slightly less abstract than Solutions and Venues, as they are just that - a Building, both in real life and in the MapsIndo
cc. @markhougaard A bit unsure if "Outside" should be included, and what to say about it.

2022-03-24 07:43 UTC, Chatrine commented on src/cms/index.md
> +  * Floors are the levels that exist within a Building. A Building might only have one Floor, but it could also have 50 or more! That entirely depends on the size of the Building in question.
```suggestion
  * Floors are the levels that exist within a Building. A Building has at least one Floor. 
```

2022-03-24 07:45 UTC, Chatrine commented on src/cms/index.md
> +  * Locations can be split into two seperate types - Rooms and Points of Interest (POI's).
```suggestion
  * Locations can be split into two separate types - Rooms and Points of Interest (POIs).
```

2022-03-24 07:47 UTC, Chatrine commented on src/cms/index.md
> +    * A Room is just that, a data point with a defined boundary, often corresponding to the walls of the physical Room. This could be a meeting room, or a bathroom.
```suggestion
    * A Room is a data point with a defined boundary, often corresponding to the walls of the physical Room. This could e.g. be a meeting room, or a bathroom.
```

2022-03-24 10:10 UTC, Chatrine commented on src/cms/index.md
> +    * A POI is a more non-specifc Location, that doesn't necesarily havce a physcially constraining factor such as walls. An example of this could be a water cooler in an office - It's a physical loc
```suggestion
    * A POI is a point on the Map that can be added and moved in the CMS. POIs do not have any polygon data as it consists of only one point. Some examples of POIs are locations that are not available in Floor plan drawings, such as coffee machines, food trucks, or temporary event structures. 
```

2022-03-24 11:29 UTC, Chatrine commented on src/cms/index.md
> +There are several main pages in the CMS, those being "Map", "Solution Details" and "Deployment". "Solution Details" and "Deployment have further subpages. The heirachial structure is like this:
Should we leave out the "Deployment stuff"? It does not matter to external users, right @markhougaard?

2022-03-24 11:32 UTC, JG1995 commented on src/cms/index.md
> +There are several main pages in the CMS, those being "Map", "Solution Details" and "Deployment". "Solution Details" and "Deployment have further subpages. The heirachial structure is like this:
I think Mark and I already agreed that it shouldn't be there, I think I just forgot to remove it after I learned that it wasn't visible to users... So that's just my bad!

2022-03-24 11:39 UTC, Chatrine commented on src/cms/index.md
> +* **Solution Details** - A "behind-the-scenes" page, where you administrate things such as categories, types, visibility, etc.
```suggestion
* **Solution Details** - A "behind-the-scenes" page, where you administrate things such as Categories, Types, Visibility, etc.
```

2022-03-24 11:43 UTC, Chatrine commented on src/cms/index.md
> +  * **Types** - Define "types" of location, such as "Canteen", "Bathroom", etc.
```suggestion
  * **Types** - Defines "types" of Locations. Types work as specific identifiers for a group of Locations such as "Canteen", "Bathroom", etc.
```

2022-03-24 11:49 UTC, Chatrine commented on src/cms/index.md
> +  * **Categories** - Similar to types, but in a broader sense - The types "Male Bathroom" and "Female Bathroom" might both belong to the category "Toilets".
```suggestion
  * **Categories** - Categories are a way to group or organize Locations for easier searching in your application. Categories can be used to group Locations in bundles regardless of their Type. The Types "Male Bathroom" and "Female Bathroom" might both belong to the Category "Toilets".
```

2022-03-24 11:53 UTC, Chatrine commented on src/cms/index.md
> +  * **Type Visibility** - Define the zoom levels for which each type will appear on the map.
```suggestion
  * **Type Visibility** - Defines the Zoom Levels for which the Locations of each Type will appear on the Map.
```

2022-03-24 11:55 UTC, Chatrine commented on src/cms/index.md
> +  * **Buildings** - A list of the buildings present in your venue.
```suggestion
  * **Buildings** - An overview of the Buildings present in your Venue.
```

2022-03-24 11:57 UTC, Chatrine commented on src/cms/index.md
> +  * **Venues** - A list of venues present in your solution.
```suggestion
  * **Venues** - An overview of the Venues present in your Solution.
```

2022-03-24 11:59 UTC, Chatrine commented on src/cms/index.md
> +  * **Export Map** - Generates a high-resolution image of your map, suitable for, for example, printing.
```suggestion
  * **Export Map** - Generates a high-resolution image of your Map, suitable for printing or similar.
```

2022-03-24 12:00 UTC, Chatrine commented on src/cms/index.md
> +  * **App Settings** - A page of various settings concerning your app.
```suggestion
  * **App Settings** - A page with various settings concerning your app.
```

2022-03-24 12:02 UTC, Chatrine commented on src/cms/index.md
> +    * **Booking Provider** - Settings for the booking provider you use (if used) for your solution.
```suggestion
    * **Booking Provider** - Settings for the booking provider you use for your Solution.
```

2022-03-24 12:04 UTC, Chatrine commented on src/cms/index.md
> +    * **Position Provider** - Settings for the position provider you use (if used) for your solution.
```suggestion
    * **Position Provider** - Settings for the position provider you use for your Solution.
```

2022-03-24 12:04 UTC, Chatrine commented on src/cms/index.md
> +    * **Webex** - Settings for your Cisco Webex Integration (if used).
```suggestion
    * **Webex** - Settings for your Cisco Webex Integration.
```

2022-03-24 12:11 UTC, Chatrine commented on src/cms/index.md
> +Keep in mind, that there are 2 different roles in the system, that may impact which options you have access to. This documentation will be written from the perspective of an **Admin** level user.
```suggestion
In the CMS there are different levels of users, which has an effect on what you have access to. This documentation is written with an **Admin** user level in mind.
```

2022-03-24 12:14 UTC, Chatrine commented on src/cms/index.md
> +* **Admin** - Administrators have editor rights and have access to further settings in the CMS
Maybe give an example?

2022-03-24 12:48 UTC, Chatrine commented on src/cms/index.md
> +This is the main navigation of the MapsIndoors CMS. The map present will depend on the map you have uploaded in your Solution, but the overlay will remain the same.
```suggestion
The Map section is the main navigation of the MapsIndoors CMS and includes the Filter bar at the top, Toolbar at the bottom, a Floor selector on the right, and your Map in the center.
```

2022-03-24 12:54 UTC, Chatrine commented on src/cms/index.md
> +1. A button to return you to the main menu.
This is not a button, nothing happens if you click on it. This should be deleted.

2022-03-24 12:57 UTC, Chatrine commented on src/cms/index.md
> +![map-main](/assets/cms/interface-overview/Map_Main.png)
It is a little difficult to see the red numbers on the green color. Maybe you could try out another red color, e.g. use Figma for quick and easy editing.

2022-03-24 13:03 UTC, Chatrine commented on src/cms/index.md
> +1. Enter the "Map" view (the currently active one in the screenshot).
```suggestion
1. Enters the "Map" view (shown on the image). This is the page you see when logging into the CMS.
```

2022-03-24 13:06 UTC, Chatrine commented on src/cms/index.md
> +1. Enter the "Solution Details" menu.
```suggestion
1. Enters the "Solution Details" menu containing the submenus mentioned earlier.
```

2022-03-24 13:13 UTC, Chatrine commented on src/cms/index.md
> +1. View a sample Web App using the information entered in the CMS.
This is not included in the "current" documentation, please check if it should be included.

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. "Edit Display Settings" - The ability to modify the Display Settings for a given type - See more detailed information on Display Settings here.
Remember to make the "here" text into a link.

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. The icon assigned to the Type.
```suggestion
1. The Icon assigned to the Type.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. Displays how the Label is displayed on your map - Usually either Location name, or not displayed at all.
```suggestion
1. Displays what information the Type's Label contains when displayed on your Map.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. The number of Locations in the given Type.
```suggestion
1. The number of Locations with the given Type applied.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +Categories are similar to Types, but whereas Locations can only be of one Type, they can be of multiple Categories, and would usually be used as a form of "tags" when searching - For example, a cante
```suggestion
Categories are similar to Types, but whereas Locations can only be of one Type, they can be of multiple Categories. Categories are used for browsing important Locations, or amenities, in your application. - For example, a canteen might be in a Category of both "Food" and "Leisure", but still only be of the Type "Canteen".
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +Type Visibility is the term used to determine at which zoom levels both Names and Labels are visible, determined per Type.
```suggestion
Type Visibility is the term used to determine at which Zoom Levels both the Types' Icons and Labels are visible.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +#### Type Visibility
Please check if this section should still be included or not. @markhougaard will know if we keep or delete the page.

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. Hide/Unhide - Click or unclick this if you don't want a specific Type to show up on the map at all.
```suggestion
1. Visibility toggle - Click to toggle on/off the Type visibility. It controls whether the Type Icons and Labels are shown on the Map
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. Set the minimum and maximum zoom level at which a given Type should be visible.
```suggestion
1. Set the minimum and maximum Zoom Level at which a given Type should be visible.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +This page provides you with a list of Buildings in your Solution.
```suggestion
This page provides you with a list of the Buildings in the selected Venue in your Solution.
```

2022-03-25 07:55 UTC, Chatrine commented on src/cms/index.md
> +1. Add a new Building.
Please check if this is still there. I think this is already or should be removed. cc @markhougaard

2022-03-25 10:22 UTC, Chatrine commented on src/cms/index.md
> +* **Location**: A term used for all Rooms and points of interest (POI).
```suggestion
* **Location**: A term used for all Rooms and Points of Interest (POI).
```

2022-03-25 10:22 UTC, Chatrine commented on src/cms/index.md
> +* **POI**: "Point of interest” - is usually an object that isn't tied to a room. E.g. Vending Machine, Locker, A Statue, ATM etc.
```suggestion
* **POI**: "Point of interest” - is usually an object that isn't tied to a Room. E.g. Vending Machine, Locker, A Statue, ATM etc.
```

2022-03-25 10:22 UTC, Chatrine commented on src/cms/index.md
> +* **Type**: All Locations are of a type. Types serve as templates for Locations to provide a basic setup. Many of the properties can later be overridden for specific Locations.
```suggestion
* **Type**: All Locations are of a Type. Types serve as templates for Locations to provide a basic setup. Many of the properties can later be overridden for specific Locations.
```

2022-03-28 11:54 UTC, JG1995 commented on src/cms/index.md
> +If you want to see a history of that specific Location this ID can be used to filter by
Good question - This section was copied from existing Documentation, so I'm not entirely sure what's supposed to be there...

2022-03-28 11:55 UTC, JG1995 commented on src/cms/index.md
> +1. "Edit Role" - Edit settings pertaining to one specific App User Role.
That's not what the button is called though - Has it changed since I wrote this initial text?

2022-03-28 11:56 UTC, JG1995 commented on src/cms/index.md
> +![map-toolbar](/assets/cms/interface-overview/Map_Toolbar.png)
Of course, this will be handled tomorrow.

2022-03-29 07:40 UTC, JG1995 commented on src/cms/index.md
> +  * A Venue is the second level of data. A Venue might consist of only one Building, but it could also consist of several, for example, a university campus might be many Buildings, but it is all cons
Just for Venues point

2022-03-29 07:40 UTC, JG1995 commented on src/cms/index.md
> +1. View a sample Web App using the information entered in the CMS.
We ask Mark

2022-03-29 07:43 UTC, JG1995 commented on src/cms/index.md
> +1. Add a new Building.
Yes, remove

2022-03-29 07:46 UTC, JG1995 commented on src/cms/index.md
> +If you want to see a history of that specific Location this ID can be used to filter by
Just delete this sentence.

2022-03-29 19:57 UTC, markhougaard requested changes

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +The MapsIndoors Content Management System (CMS) enables you to add, edit, and maintain your location data within the MapsIndoors platform.
```suggestion
The MapsIndoors Content Management System (CMS) enables you to add, edit, and maintain your data within the MapsIndoors platform.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +  * A Solution is the topmost level of your data structure. It encompasses all of the Venues, Buildings and Locations that you need for your MapsIndoors implementation. It is possible to have more th
```suggestion
  * A Solution is the topmost level of your data structure. It encompasses all of the Venues, Buildings and Locations that you need for your MapsIndoors implementation. It is possible to have more than one Solution, but for the vast majority of use-cases, you will just have one.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +  * A Venue is the second level of data. You can have multiple Venues in one solution. For example, a large company might have multiple offices spread over the country. Each of these could be a Venue
```suggestion
  * A Venue is the second level of data. You can have multiple Venues in one Solution. For example, a large company might have multiple offices spread over the country. Each of these could be a Venue, but under the same Solution. A Venue can consist of one or more Buildings. For example, a sports stadium might be many Buildings, but it is all considered the same Venue.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +  * Locations can be split into two separate types - Rooms and Points of Interest (POIs).
```suggestion
  * There are three kinds of Locations: Rooms, Areas, and Points of Interest (POIs).
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +    * A Room is a data point with a defined boundary, often corresponding to the walls of the physical Room. This could e.g. be a meeting room, or a bathroom.
```suggestion
    * A Room is a multi-point polygon, representing the walls of the physical Room, like a meeting room, or a restroom.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +    * A POI is a point on the Map that can be added and moved in the CMS. POIs do not have any polygon data as it consists of only one point. Some examples of POIs are locations that are not availabl
```suggestion
    * A POI is a point on the map that can be added and moved in the CMS. POIs do not have any polygon data as it consists of only one point. Some examples of POIs are locations that are not available in floor plan drawings, such as coffee machines, food trucks, or temporary event structures.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +There are two main pages in the CMS, "Map" and "Solution Details". The heirachial structure is like this:
```suggestion
There are two main pages in the CMS, "Map" and "Solution Details". The hierarchical structure is like this:
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +* **Map** - The main page, this is where you manage your Map.
```suggestion
* **Map** - The main page where you manage your data on the map.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +* **Solution Details** - A "behind-the-scenes" page, where you administrate things such as Categories, Types, Visibility, etc.
```suggestion
* **Solution Details** - A "behind-the-scenes" page, where you administer Categories, Types, App Settings, etc.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +  * **Categories** - Categories are a way to group or organize Locations for easier searching in your application. Categories can be used to group Locations in bundles regardless of their Type. The T
```suggestion
  * **Categories** - Categories are a way to group or organize Locations for easier browsing in your application. Categories can be used to group Locations in bundles regardless of their Type.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +  * **Export Map** - Generates a high-resolution image of your Map, suitable for printing or similar.
```suggestion
  * **Export Map** - Generates a high-resolution image of your Map, suitable for printing or similar. *Note*: Not available for all customers.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +In the CMS there are different levels of users, which has an effect on what you have access to. For example, an "Admin" level user has access to Solution-level settings, wherean an "Editor" primarily
```suggestion
In the CMS there are different levels of users, which has an effect on what you have access to. For example, an "Admin" level user has access to Solution-level settings, whereas an "Editor" primarily has access to create and edit Locations on the Map. This documentation is written with an **Admin** user level in mind.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. Select one or more Floors.
```suggestion
1. Select one or more Floors. This is active when a single Building is selected.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +Working left to right, the functionality in this main Toolbar is as follows - You can also hover over the icons in the CMS to see their names.
```suggestion
From left to right, the functionalities in the Toolbar are as follows (you can also hover over the icons in the CMS to see their names):
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +* **Add Barrier Route Element** - Creates a Route Element on your map - The Barrier Route Element can be used to apply e.g. restrictions, delay, or one way direction to specific parts of the Network.
```suggestion
* **Add Barrier Route Element** - Creates a Route Element on your map. The Barrier Route Element can be used to apply e.g. restrictions, delay, or define one way direction to specific parts of the Network. For example, if you do not want your directions to guide your visitors down a specific hallway, but there isn't a Door present, this Route Element can be used.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. "Edit Display Rules" - The ability to modify the Display Rules for a given Type - See more detailed information on Display Rules [here]({{site.url}}/various/display-rules/).
```suggestion
1. "Edit Display Rules" - The ability to modify the Display Rules for a given Type. Read more about [Display Rules]({{site.url}}/various/display-rules/).
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +Categories are similar to Types, but whereas Locations can only be of one Type, they can be of multiple Categories. Categories are used for browsing important Locations, or amenities, in your applica
```suggestion
Categories are similar to Types, but whereas Locations can only be of one Type, they can be of multiple Categories. Categories are used for browsing important Locations, or amenities, in your application. For example, a Canteen might be in a Category of both "Food" and "Leisure", but still only be of the Type "Canteen".
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. A save button, click this to save your changes.
```suggestion
1. A save button. Click this to save your changes.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. Visibility toggle - Click to toggle on/off the Type visibility. It controls whether the Type Icons and Labels are shown on the Map
```suggestion
1. Visibility toggle. Click to toggle on/off the Type visibility. It controls whether the Type Icons and Labels are shown on the Map
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. "Edit Building" - Let's you edit the properties of the Building, such as name, ID and Floors.
```suggestion
1. "Edit Building". Lets you edit the properties of the Building, such as name, ID and Floors.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +A page featuring a list of Venues in your Solution. These are provided by MapsIndoors, too add more, contact your representative.
```suggestion
A page featuring a list of Venues in your Solution. These are provided by MapsIndoors, and to add more, contact your representative.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. "Edit Venue" - You can e.g. edit Venue Name and Venue External ID in the Venue details editor.
```suggestion
1. "Edit Venue". You can e.g. edit Venue Name and Venue External ID in the Venue details editor.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +1. "Edit Role" - Edit settings pertaining to one specific App User Role.
```suggestion
1. "Edit Role". Edit settings pertaining to one specific App User Role.
```

2022-03-29 19:57 UTC, markhougaard commented on src/cms/index.md
> +Allows Admins, to control who has access and what roles they have, or create new users.
```suggestion
Allows Admins to control who has access, and what roles they have, as well as create new users.
```

2022-03-30 08:11 UTC, markhougaard approved these changes

2022-03-30 08:12 UTC, merged