Feature/simple map app
MapsPeople/docs pull request #834
Opened 2022-04-08 13:39 UTC by JG1995

Based on the very helpful README files you guys provided, re-written in a slightly more user-friendly way. Give it a read through, make sure it still checks out :-)

The actual links to the repo's are of course still missing, but they'll be added when they're ready.

2022-04-08 13:47 UTC, Malte-MapsPeople approved these changes

2022-04-08 13:49 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +The solution is pre-made, and simply needs integration into your existing app. Please note, that this solution is not intended to be customised. If you need additional features, or wish to customise
Its just a normal app, they can take it and do all they changes they wish from there on. Should not be an issue.

2022-04-08 13:50 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +First, you need to download or clone the pre-made feature from GitHub, found [here](*INSERT ANDROID REPO LINK HERE*).
repository/project, this is not really a feature

2022-04-08 13:51 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +* For the next step, this tutorial assumed that you use [Glide](https://bumptech.github.io/glide/) for image handling in your application. If you are not using Glide, either import it, or if you use
assumed, should this not be assumes? :D 
Anyway, i'd just leave it at this project uses.

2022-04-08 13:52 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +> NOTE: Other view and image dependancies may be needed, depending on how your current app is implemented.
Not sure what this means?

2022-04-08 13:55 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +* Check the `FirstFragment.kt` class on how to apply User Roles to the map fragment. The Accessibility User Role, which you can use to designate accesible routes might avoid stairs, for example, is h
Remove the accesibilty comment. That is specific to the "old" implementation

2022-04-08 14:00 UTC, JG1995 commented on src/content/map/simple-map-app.md
> +> NOTE: Other view and image dependancies may be needed, depending on how your current app is implemented.
You wrote it though? From line 25 in the README: "Note the other view and material dependencies might be needed depending on you current app implementation"

Did I misunderstand something and reworded it wrong?

2022-04-08 14:05 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> +> NOTE: Other view and image dependancies may be needed, depending on how your current app is implemented.
Yes, Material is a specific android library that is used for a lot of ui. Depending on the version of that library the UI can look/behave differently. https://material.io/develop/android

2022-04-08 14:10 UTC, timMikkelsen commented on src/content/map/simple-map-app.md
> -* Check the `FirstFragment.kt` class on how to apply User Roles to the map fragment. The Accessibility User Role, which you can use to designate accesible routes might avoid stairs, for example, is h
Check the `FirstFragment.kt` class on how to apply User Roles to the map fragment. 
This was still valid 🙈

2022-04-12 11:56 UTC, markhougaard requested changes

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +The **Simple Map App** is a plug-and-play solution for you to have a simple integration of a map, containing a basic search and directions functionality, in your existing app. While you can work on i
```suggestion
The **Simple Map App** is a plug-and-play solution for you to have a simple integration of a map, containing basic search and directions functionalities, in your existing app. While you can work on implementing your own solution using the documentation found [here]({{site.url}}/content/map/), if you just need a simple solution with no further customisation required, this should fulfil your needs.
```

Can we find another word than "solution" here, as it conflicts quite a bit with our term "Solution"?

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +The solution is pre-made, and simply needs integration into your existing app. If you wish further features, or customise existing ones, we suggest creating your own implementation, or modifying this
```suggestion
The solution is pre-made, and only needs to be integrated into your existing app. If you need further features, or want to customize existing ones, you're free to modify this one to your needs.
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +First, you need to download or clone the pre-made project from GitHub, found [here](*INSERT ANDROID REPO LINK HERE*).
```suggestion
First, download or clone the pre-made project from GitHub: [link](*INSERT ANDROID REPO LINK HERE*).
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Add the following dependencies from `build.gradle`:
```suggestion
* Open the project you just downloaded, and copy the classes located in `java/com/mapspeople/sportseventactivity` into your own App
* Add the Maven repository ([http://maven.mapsindoors.com/](http://maven.mapsindoors.com/)) to your project's `build.gradle` file
* Add the following dependencies from `build.gradle`:
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Add the API key to the manifest file under the `Application` tag like so:
```suggestion
* Copy the layout and drawables from the `res` folder into your app
* Copy the `String` values from `res/values` into your app
* Copy the `google_maps_api.xml` file to your project and insert a valid Google Maps API key - [See more info on how to do that here.]({{site.url}}/content/getting-started/android/prerequisites/)
* Add the API key to the manifest file under the `Application` tag like so:
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Check the `FirstFragment.kt` class on how to apply User Roles to the map fragment.
```suggestion
* Change the places where the navigation graph is used, if you are not using navigation. Alternatively, create a navigation action for MapsFragment. If so, change the navigation controller call on `line: 74` inside `MapsFragment.kt` under the TODO
* Check the `FirstFragment.kt` class on how to apply User Roles to the map fragment
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +First, you need to download or clone the pre-made project from GitHub, found [here](*INSERT IOS REPO LINK HERE*).
```suggestion
First, download or clone the pre-made project from GitHub: [link](*INSERT IOS REPO LINK HERE*)
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Add your MapsIndoors API key and Google Maps API key to the `MapsIndoors-Info.plist` file. Then run the project.
```suggestion
* Follow the description in the [MapsIndoors Getting Started guide](https://docs.mapsindoors.com/ios/v3/getting-started/prerequisites/) to get an API key for MapsIndoors and Google
* From the terminal, in the path you cloned the repository to, run `pod install`
* Open the file `xxxxx.xcworkspace` in Xcode, or your editor of choice
* Make a copy of the `MapsIndoors-Info-Sample.plist` file and name it `MapsIndoors-Info.plist`
* Add your MapsIndoors API key and Google Maps API key to the `MapsIndoors-Info.plist` file and run the project
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Update your podfile so it matches the podfile in the MapsIndoors SwiftUI App Example.
```suggestion
* To reuse the code in your app, drag and drop the `Views` and `Services` folders, and all the `Assets` except for the `AppIcon` into your project
* Create a copy of the `MapsIndoors-Info-Sample.plist` file and name it `MapsIndoors-Info.plist`
* Add your MapsIndoors API key and Google Maps API key to the `MapsIndoors-Info.plist` file
* Look at `ViewController.swift` for an example of how to initialize the MapsIndoors SDK and use the MapsIndoors SwiftUI implementation in an UIKit app. The `ViewController.swift` reads the API keys retrieved as described above from the file `MapsIndoors-Info.plist`
* Update your podfile so it matches the podfile in the MapsIndoors SwiftUI App Example
```

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +![ios-single-page-app](/assets/single-page-app/iOS_Single_Page_App.png)
Remember to make this url relative with `{{ site.url }}`

2022-04-12 11:56 UTC, markhougaard commented on src/content/map/simple-map-app.md
> +* Follow the description in the [MapsIndoors Getting Started guide](https://docs.mapsindoors.com/ios/v3/getting-started/prerequisites/) to get an API key for MapsIndoors and Google.
Remember to make this url relative with `{{ site.url }}`

2022-04-21 07:38 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +> NOTE: This Fragment was designed to be displayed in Portrait Mode. While it will work in Landscape Mode, some UI elements may look distorted or out-of-place.
```suggestion
> NOTE: This app is designed to be displayed in Portrait Mode. While it will work in Landscape Mode, some UI elements may look distorted or out-of-place.
```

2022-04-21 07:38 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +This app will provide an example of how to use the MapsPeople SDK in SwiftUI.
```suggestion
This app provides an example of how to use the MapsIndoors SDK in SwiftUI.
```

2022-04-21 07:43 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +The **Simple Map App** is a plug-and-play solution for you to have a simple integration of a map, containing basic search and directions functionalities, in your existing app. While you can work on i
```suggestion
The **Simple Map App** is both a full app and plug-and-play code for you to integrate basic usage of MapsIndoors, containing search and directions functionalities, in your existing app. If you just want to get started with a simple solution with no customisation, this should fulfil your needs. Going through this guide will also teach you some principles on how MapsIndoors interacts with an app, and is a natural next step after the "Getting Started" guides.

If you need more customisation you can implementing your own solution using the documentation found [here]({{site.url}}/content/map/), or modify this code as needed.
```

2022-04-21 07:45 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +* Look at `ViewController.swift` for an example of how to initialize the MapsIndoors SDK and use the MapsIndoors SwiftUI implementation in an UIKit app. The `ViewController.swift` reads the API keys
```suggestion
* Look at `ViewController.swift` for an example of how to initialize the MapsIndoors SDK and use the **Simple Map App** implementation in an UIKit app. The `ViewController.swift` reads the API keys retrieved as described above from the file `MapsIndoors-Info.plist`
```

2022-04-21 07:45 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +* Update your podfile so it matches the podfile in the MapsIndoors SwiftUI App Example
```suggestion
* Update your podfile so it matches the podfile in the MapsIndoors **Simple Map App**
```

2022-04-21 07:47 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/simple-map-app.md
> +## Prerequisites
Can this whole section not be a shared section that is being reused between all SDKs and this "Simple Map"?

2022-04-21 08:04 UTC, JG1995 commented on src/content/getting-started/simple-map-app.md
> +## Prerequisites
It was, it's used in the Getting Started guides, but some slight wording changes was made for this one so I had to put it in manually 🙂

2022-04-27 12:58 UTC, merged