Update/standard app to template app
MapsPeople/docs pull request #862
Opened 2022-06-15 13:55 UTC by JG1995

We're moving away from advertising our Standard/PoC apps to customers, at least on mobile, and replacing it with our MapsIndoors Templates. Have changed a number of files to reflect this. Initially, it seems that it was also intended to change code samples involving the standard apps, but I don't seem to be able to find any.

2022-06-16 07:05 UTC, markhougaard requested changes

2022-06-16 07:05 UTC, markhougaard commented on src/product/index.md
> +The MapsIndoors Template is both a full app and plug-and-play code for you to integrate basic usage of MapsIndoors, containing search and directions functionalities, in your existing app. If you just
I'm quite concerned about using the term "full app" here, as I think it could lead to some confusion on its exact purpose. I'm aware that it can stand alone, or be a "page" in an existing app, but we probably need more words on the fact that it's a starting point, not a destination.

2022-06-16 07:05 UTC, markhougaard commented on src/product/index.md
> +For web development, instead of the MapsIndoors Template, a MapsIndoors "Standard App" with similar functionality also includes a plug-and-play Kiosk web app. This browser-based app can run on an inf
```suggestion
For web development, instead of the MapsIndoors Template, a MapsIndoors "Showcase App" with similar functionality, as well as a plug-and-play Kiosk web app exists.
```

Let's write less about the Kiosk 🙂

2022-06-16 07:05 UTC, markhougaard commented on src/content/cms/index.md
> +> NOTE: Do not set an Alias if you want to make it more difficult to find and load your MapsIndoors data in a regular app. In that case, you should only load the data with an API key.
```suggestion
> NOTE: Do not set an Alias if you want to make it more difficult to find and load your MapsIndoors data. In that case, you should only load the data with an API key.
```

2022-06-16 07:26 UTC, JG1995 commented on src/product/index.md
> +The MapsIndoors Template is both a full app and plug-and-play code for you to integrate basic usage of MapsIndoors, containing search and directions functionalities, in your existing app. If you just
The first part of this paragraph is taken directly from where we first introduced the Template app, as an addition to the Getting Started guide. The wording has been through several rounds of review and approval, so if it's to be changed here, I think another larger discussion needs to be had about how we talk about and refer to the Template app in general 🙂

2022-06-17 09:15 UTC, markhougaard approved these changes

2022-06-17 09:19 UTC, merged