Feature/v4 migration guide
MapsPeople/docs pull request #869
Opened 2022-06-23 11:34 UTC by JG1995

v3 -> v4 migration guide, should be finished. Give it a read through.

It's currently hidden from the menus on the site, but is accessible (once merged) through: https://docs.mapsindoors.com/content/getting-started/v4-migration-guide/

2022-06-23 11:43 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +The Android SDK for MapsIndoors has been upgraded from V3 to V4, which comes with a lot of improvements to stability and flexibility. SDK loading has been improved, and is less error-prone. This guid
Improvements to stability and less error prone, should be internal only IMO. 

Lets stay to what the V4 brings for convenience and features. We now have the possibility to use MapBox with MapsIndoors as well as multiple interfaces have been refactored to simplify development and SDK behaviour when developing as well as removing redundant boiler plate code

2022-06-23 11:46 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +In V4, these settings have been moved to `MPSolutionConfig`, which is located on the MPSolution, in this version these settings have [something about boolean and enum]. They can be fetched and update
something about boolean and enum?

2022-06-23 11:51 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +In V4, the solution config will ship with a Main Display Rule, which is used to define the display rule "ground truths" for the solution. Fields in this display rule must not be `null`. If a display
which is used to define the display rule "ground truths" for the solution.

which is used to define the defaults for location and type display rules, when nothing is declared on the specific display rule

2022-06-23 11:53 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +In V4, this has been simplified somewhat. Given a route, you can instantiate a new `MPDirectionsRenderer`, and set the route using `setRoute()`. Use the `MPDirectionsRenderer` object to navigate thro
somewhat seems redundant.

2022-06-23 11:54 UTC, JG1995 commented on src/content/getting-started/v4-migration-guide.md
> +In V4, these settings have been moved to `MPSolutionConfig`, which is located on the MPSolution, in this version these settings have [something about boolean and enum]. They can be fetched and update
Matias will fix this 😄

2022-06-23 13:05 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +The Android SDK for MapsIndoors has been upgraded from V3 to V4, which comes with a lot of improvements features and flexibility. The MapsIndoors SDK now supports Mapbox as a map provider, alongside
improvements, features. 

which comes with improved interfaces and flexibility for developing your own map experience.
@fhansenMP @matiasholst Thoughts?

2022-06-23 13:48 UTC, matiasholst submitted a review, later dismissed

2022-06-23 13:55 UTC, matiasholst commented on src/content/getting-started/v4-migration-guide.md
> +The Android SDK for MapsIndoors has been upgraded from V3 to V4, which comes with a lot of improvements features and flexibility. The MapsIndoors SDK now supports Mapbox as a map provider, alongside
yes

2022-06-24 06:59 UTC, ChristianWolf-mapspeople requested changes

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +The Android SDK for MapsIndoors has been upgraded from V3 to V4, which comes with a lot of improvements features and flexibility. The MapsIndoors SDK now supports Mapbox as a map provider, alongside
```suggestion
The Android SDK for MapsIndoors has been upgraded from V3 to V4, which comes with a lot of improvements, features and flexibility. The MapsIndoors SDK now supports Mapbox as a map provider, alongside some reworked and refactored features that simplify development and SDK behavior. This guide will cover specific changes to the SDK and how to use it to provide you with a guide on how to upgrade from V3 to V4.
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +--->
This should not be commented out since both map engines are available.

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +In this new version of the SDK, initialization is started by the new function `MapsIndoors.load()`:
```suggestion
In V4, initialization is started by the new function `MapsIndoors.load()`:
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +Map-engine-specific API keys are handled by `MPMapConfig`, covered in the "MapControl Initialization" section of this guide.
```suggestion
Map engine specific API keys are handled by `MPMapConfig`, covered in the "MapControl Initialization" section of this guide.
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +MapControl instantiation and initialization are separate concepts. You create a new instance of `MapControl` and configure it with a map and view - optionally you could set clustering, overlapping or
```suggestion
MapControl instantiation and initialization are separate concepts. You create a new instance of `MapControl` and configure it with a map and view - optionally you could set clustering, overlapping and other behavior on the object.
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +In V3, `MapControl` is a separate asynchronous call:
```suggestion
In V3, `MapControl.init()` is a separate asynchronous call:
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +With a `MPMapConfig` instance, you may create a new `MapControl` instance. This now happens through a factory pattern. This both instantiates and initializes your `MapControl` object asynchronously.
```suggestion
With a `MPMapConfig` instance, you may create a new `MapControl` instance. This now happens through a factory pattern. This both instantiates and initializes your `MapControl` object asynchronously. If everything succeed, you will receive a ready-to-use `MapControl` instance - if not, you will get an error and receive no `MapControl` instance.
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +## MapsIndoors SDK Map Engine Flavours
```suggestion
## MapsIndoors SDK Map Engine Flavors
```

2022-06-24 06:59 UTC, ChristianWolf-mapspeople commented on src/content/getting-started/v4-migration-guide.md
> +In V4, these settings have been moved to `MPSolutionConfig`, which is located on the MPSolution, in this version these settings have types (a boolean and an Enum type). This helps ensure that these s
```suggestion
In V4, these settings have been moved to `MPSolutionConfig`, which is located on the MPSolution. Now these settings have types (a boolean and an Enum type). This helps ensure that the settings are easier to configure and have no parsing errors. They can be fetched and updates like this:
```

2022-06-24 07:42 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +<!--- This part is not 100% settled, be sure to talk to Frederik to confirm before release!
With the release of V4 the MapsIndoors SDK is released as two separate libraries depending on the Map Provider.
You can get them through Maven by changing your dependency to get:

```java
implementation 'com.mapspeople.mapsindoors:googlemapssdk:4.0.0-beta.9'

implementation 'com.mapspeople.mapsindoors:mapboxsdk:4.0.0-beta.9'
´´´

2022-06-24 08:17 UTC, timMikkelsen commented on src/content/getting-started/v4-migration-guide.md
> +Both of these are distributed through Maven, and come packaged with a number of helper classes.
This is slightly redundant by the line above now i guess

2022-06-24 08:24 UTC, timMikkelsen approved these changes

2022-06-24 08:33 UTC, ChristianWolf-mapspeople approved these changes

2022-06-24 08:37 UTC, matiasholst approved these changes

2022-06-24 08:37 UTC, fhansenMP approved these changes

2022-06-24 10:02 UTC, merged