Add/blue dot cisco dna web
MapsPeople/docs pull request #903
Opened 2022-08-10 11:53 UTC by JG1995

I took the code snippets, inserted them, and rewrote the text to suit Web-named variables to the best of my ability - I hope it makes sense, but maybe not.

2022-08-11 08:39 UTC, eNepper requested changes

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +In order to show a user's position in an indoor map with MapsIndoors, a Position Provider must be implemented. MapsIndoors does not implement a Position Provider itself, but rely on 3rd party positio
It says something about iOS at the end of this line.

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +In order to show a user's position in an indoor map with MapsIndoors, a Position Provider must be implemented. MapsIndoors does not implement a Position Provider itself, but rely on 3rd party positio
It could say something like: `In an outdoor environment, this Position Provider can be a wrapper of the browser's native Geolocation API` https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +![cisco-dna-ios](/assets/map/positioning/positioning-diagram.png)
```suggestion
```

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +A Position Provider in MapsIndoors must adhere to the `MPPositionProvider` protocol. Once you have an instance of an `MPPositionProvider` you can register it by assigning it to `MapsIndoors.positionP
`MPPositionProvider` Is not a known interface in the JSSDK

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +A Position Provider in MapsIndoors must adhere to the `MPPositionProvider` protocol. Once you have an instance of an `MPPositionProvider` you can register it by assigning it to `MapsIndoors.positionP
I don't think we have an official interface for this in the JSSDK

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +     * @private
This comment should be moved into the next code section as it belongs to the _errorHandler function

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +        const clientIp = '10.0.0.134';
The customer is responsible for implementing a way of getting hold of the client/device's IP address because it is not accessible from within the browser. It could be a service on the local network that can reply with the IP address of the device calling the service.

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +The `CiscoDNAPositionProvider2` communicates with some MapsIndoors services to get the Cisco device id, and uses a message subscription service (MQTT) to subscribe for position updates. Each time a C
```suggestion
```

2022-08-11 08:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +Just like in the mock Position Provider example, we need to implement a Position Provider that wraps the MapsIndoors CiscoDNA services to inject the CiscoDNA indoor positioning into MapsIndoors. If y
I think this part should be rewritten because it also refers to iOS

2022-08-15 08:42 UTC, JG1995 commented on src/content/map/positioning/cisco-dna.md
> +Just like in the mock Position Provider example, we need to implement a Position Provider that wraps the MapsIndoors CiscoDNA services to inject the CiscoDNA indoor positioning into MapsIndoors. If y
Can you elaborate on how it should be rewritten? I removed the direct references to iOS, but I assume many of the names given also don't exist for web, like we already removed some of them.

2022-08-18 10:36 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +In order to show a user's position in an indoor map with MapsIndoors, a Position Provider must be implemented. MapsIndoors does not implement a Position Provider itself, but rely on 3rd party positio
```suggestion
In order to show a user's position on an indoor map with MapsIndoors, a Position Provider must be implemented. MapsIndoors does not implement a Position Provider itself, but rely on 3rd party positioning software to create this experience. In an outdoor environment, this Position Provider can be a wrapper of the browser's native Geolocation API.
```

2022-08-18 10:39 UTC, eNepper commented on src/content/map/positioning/cisco-dna.md
> +The Web SDK doesn't have a built-in interface like the Android and iOS SDKs. However, by following these steps, you should be able to achieve the same functionality.
```suggestion
The JavaScript SDK doesn't have a built-in interface like the Android and iOS SDKs. However, by following these steps, you should be able to achieve the same functionality.
```

2022-08-18 10:42 UTC, eNepper requested changes
I found a couple of small things

2022-08-18 10:43 UTC, merged