Add/turn off collisions zoom level migen 2381
MapsPeople/docs pull request #953
Opened 2022-11-23 11:27 UTC by JG1995

2022-11-23 11:38 UTC, matiasholst commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +```java
This is not java code, but kotlin code

2022-11-23 11:39 UTC, matiasholst commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +```java
It's the same for all the android examples

2022-11-23 11:47 UTC, matiasholst commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +    if ( zoomRange ~= (self.mapView?.camera.zoom)!) {
Does this not need an else clause to turn it off again?

2022-11-24 10:40 UTC, ChristianWolf-mapspeople requested changes
A few modifications for iOS

2022-11-24 10:40 UTC, ChristianWolf-mapspeople commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +//2. Use GMSMApViewDelegate to listen to changes in one of four events mapView:didChangeCameraPosition
```suggestion
//2. Use GMSMapViewDelegate to listen to changes in one of four events mapView:didChangeCameraPosition
```

2022-11-24 10:40 UTC, ChristianWolf-mapspeople commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +    if ( zoomRange ~= (self.mapView?.camera.zoom)!) {
I would say yes :)

2022-11-24 10:40 UTC, ChristianWolf-mapspeople commented on src/content/map/displaying-objects/turn-off-collisions-based-on-zoom.md
> +    }
```suggestion
    } else {
        MPMapControl.locationHideOnIconOverlapEnabled = false
    }
```

2022-11-25 07:13 UTC, matiasholst approved these changes

2022-11-25 08:12 UTC, merged